version: "3"

services:
  flask:
    build: ./backend
    container_name: backend
    working_dir: /app
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    env_file:
      - .env
    tty: true

  react:
    build: ./frontend
    container_name: frontend
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    tty: true